# Generated by Django 5.2.5 on 2025-09-10 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Personal biography or description', max_length=500, null=True)),
                ('image', models.ImageField(default='default.jpg', help_text='Profile picture', upload_to='profile_pics')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('student_id', models.CharField(blank=True, help_text='Student identification number (admin-only)', max_length=50, null=True)),
                ('faculty', models.CharField(blank=True, help_text='Faculty or school name (admin-only)', max_length=100, null=True)),
                ('section', models.CharField(blank=True, help_text='Academic section or class (admin-only)', max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has been verified by an administrator')),
                ('notes', models.TextField(blank=True, help_text='Administrative notes about this user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when the user was verified by an administrator', null=True)),
                ('user', models.OneToOneField(help_text='User associated with this profile', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='core_profil_user_id_155486_idx'), models.Index(fields=['is_verified'], name='core_profil_is_veri_847197_idx'), models.Index(fields=['student_id'], name='core_profil_student_9d46e4_idx')],
            },
        ),
    ]
