# Generated by Django 5.2.5 on 2025-09-07 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeexamsession',
            name='attempt',
            field=models.OneToOneField(help_text='Specific exam attempt associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to='exams.examattempt'),
        ),
        migrations.AddField(
            model_name='activeexamsession',
            name='exam',
            field=models.ForeignKey(help_text='Exam associated with this active session', on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='activeexamsession',
            name='user',
            field=models.ForeignKey(help_text='User participating in the exam session', on_delete=django.db.models.deletion.CASCADE, related_name='active_exam_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminusercreationlog',
            name='created_by',
            field=models.ForeignKey(help_text='Administrator who performed the user creation', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='Academic department offering this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.academicdepartment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(help_text='Student enrolled in the course section', limit_choices_to={'role': 'STUD'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['domain', 'is_active'], name='core_instit_domain_04ded5_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['created_at'], name='core_instit_created_1b95f1_idx'),
        ),
        migrations.AddField(
            model_name='adminusercreationlog',
            name='institution',
            field=models.ForeignKey(help_text='Institution where users were created', on_delete=django.db.models.deletion.CASCADE, related_name='creation_logs', to='core.institution'),
        ),
        migrations.AddField(
            model_name='academicdepartment',
            name='institution',
            field=models.ForeignKey(help_text='Institution that contains this academic department', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.institution'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(help_text='Educational institution the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.institution'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(help_text='Course that this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.course'),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(help_text='Instructor responsible for teaching this section', limit_choices_to={'role': 'INSTR'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(help_text='Course section the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.section'),
        ),
        migrations.AddField(
            model_name='userdevicesession',
            name='user',
            field=models.ForeignKey(help_text='User associated with this device session', on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activeexamsession',
            name='device_session',
            field=models.ForeignKey(help_text='Device session used for this exam attempt', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='core.userdevicesession'),
        ),
        migrations.AddField(
            model_name='userimporttemplate',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who created this template', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'is_active'], name='core_course_departm_61599a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='core_course_code_833bcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='adminusercreationlog',
            index=models.Index(fields=['created_by', 'created_at'], name='core_adminu_created_b53b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminusercreationlog',
            index=models.Index(fields=['institution', 'created_at'], name='core_adminu_institu_f4615f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminusercreationlog',
            index=models.Index(fields=['creation_method'], name='core_adminu_creatio_c55d17_idx'),
        ),
        migrations.AddIndex(
            model_name='academicdepartment',
            index=models.Index(fields=['institution', 'is_active'], name='core_academ_institu_2dfa06_idx'),
        ),
        migrations.AddIndex(
            model_name='academicdepartment',
            index=models.Index(fields=['code'], name='core_academ_code_cd782c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicdepartment',
            unique_together={('institution', 'code')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['institution', 'role', 'is_active'], name='core_user_institu_c1e388_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_activity'], name='core_user_last_ac_3b828a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='core_user_created_bd650f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_by'], name='core_user_created_3bcf81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('institution', 'email')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'is_active'], name='core_sectio_course__a9ab1a_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['instructor', 'is_active'], name='core_sectio_instruc_d21ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['term', 'year'], name='core_sectio_term_a12be0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_code', 'term', 'year')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='core_enroll_student_7edad6_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section', 'is_active'], name='core_enroll_section_e5c4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_on'], name='core_enroll_enrolle_8690ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'section')},
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['user', 'is_active'], name='core_userde_user_id_fa17d7_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['last_activity'], name='core_userde_last_ac_63a50a_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['device_hash'], name='core_userde_device__7e678d_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['first_seen'], name='core_userde_first_s_48e86d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevicesession',
            unique_together={('user', 'device_hash')},
        ),
        migrations.AddIndex(
            model_name='activeexamsession',
            index=models.Index(fields=['session_token'], name='core_active_session_3fead3_idx'),
        ),
        migrations.AddIndex(
            model_name='activeexamsession',
            index=models.Index(fields=['user', 'is_active'], name='core_active_user_id_f5a1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='activeexamsession',
            index=models.Index(fields=['last_activity'], name='core_active_last_ac_e2069b_idx'),
        ),
        migrations.AddIndex(
            model_name='activeexamsession',
            index=models.Index(fields=['device_session'], name='core_active_device__ec5e84_idx'),
        ),
        migrations.AddIndex(
            model_name='activeexamsession',
            index=models.Index(fields=['started_at'], name='core_active_started_5cdb6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activeexamsession',
            unique_together={('user', 'exam')},
        ),
        migrations.AddIndex(
            model_name='userimporttemplate',
            index=models.Index(fields=['is_active'], name='core_userim_is_acti_6ac186_idx'),
        ),
        migrations.AddIndex(
            model_name='userimporttemplate',
            index=models.Index(fields=['created_by'], name='core_userim_created_50d125_idx'),
        ),
    ]
