# Generated by Django 5.2.5 on 2025-08-31 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_method', models.CharField(choices=[('MANUAL', 'Manual Creation'), ('CSV_IMPORT', 'CSV Import'), ('API', 'API Integration'), ('SYSTEM', 'System Generated')], default='MANUAL', help_text='Method used for user creation', max_length=20)),
                ('users_created', models.PositiveIntegerField(default=0, help_text='Number of users successfully created')),
                ('users_failed', models.PositiveIntegerField(default=0, help_text='Number of users that failed to create')),
                ('details', models.JSONField(default=dict, help_text='Detailed information about the creation operation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Creation Log',
                'verbose_name_plural': 'User Creation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the import template', max_length=100)),
                ('description', models.TextField(help_text='Description and usage guidelines')),
                ('template_file', models.FileField(help_text='Template file for user data import', upload_to='user_templates/')),
                ('required_fields', models.JSONField(default=list, help_text='List of required field names')),
                ('optional_fields', models.JSONField(default=list, help_text='List of optional field names')),
                ('field_descriptions', models.JSONField(default=dict, help_text='Descriptions for each field')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Import Template',
                'verbose_name_plural': 'User Import Templates',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='bulkuserimport',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_by'], name='core_user_created_3bcf81_idx'),
        ),
        migrations.AddField(
            model_name='adminusercreationlog',
            name='created_by',
            field=models.ForeignKey(help_text='Administrator who performed the user creation', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminusercreationlog',
            name='institution',
            field=models.ForeignKey(help_text='Institution where users were created', on_delete=django.db.models.deletion.CASCADE, related_name='creation_logs', to='core.institution'),
        ),
        migrations.AddField(
            model_name='userimporttemplate',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who created this template', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BulkUserImport',
        ),
        migrations.AddIndex(
            model_name='adminusercreationlog',
            index=models.Index(fields=['created_by', 'created_at'], name='core_adminu_created_b53b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminusercreationlog',
            index=models.Index(fields=['institution', 'created_at'], name='core_adminu_institu_f4615f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminusercreationlog',
            index=models.Index(fields=['creation_method'], name='core_adminu_creatio_c55d17_idx'),
        ),
        migrations.AddIndex(
            model_name='userimporttemplate',
            index=models.Index(fields=['is_active'], name='core_userim_is_acti_6ac186_idx'),
        ),
        migrations.AddIndex(
            model_name='userimporttemplate',
            index=models.Index(fields=['created_by'], name='core_userim_created_50d125_idx'),
        ),
    ]
